### ISSUE TITLE
Regarding application of model to SHHS dataset

### ISSUE THREAD

**Issue by Div12345** [emadeldeen24/AttnSleep#6]
Hi, thanks for sharing the code open-source!

I was part of trying to integrate this algorithm into braindecode (https://github.com/braindecode/braindecode/pull/341#issuecomment-958721030) and while trying a test for the SHHS dataset with the sfreq = 125Hz and 30sec windows and d_model = 100, I ran into the problem where the size of data entering the layer norm was 99 and not 100. I tried tweaking the sfreq to 126 and it worked.
Any reason for this discrepancy?

Thanks in advance!

**Comment by emadeldeen24** [comment]
I guess it is a sample length issue that leads to kernel size and padding issues in MRCNN. That's why I included [MRCNN_SHHS](https://github.com/emadeldeen24/AttnSleep/blob/f993511426900f9fca20594a738bf8bee1116381/model/model.py#L333) to overcome this issue in SHHS, where I just modified the kernel size of the last Conv1d layer. You should use that and modify d_model to 100.

Hopefully this helps!
